add scala 213, and adjusted sequence of steps
Signed-off-by: YanxuanLiu <yanxuanl@nvidia.com>

diff --git a/.github/workflows/mvn-verify-check.yml b/.github/workflows/mvn-verify-check.yml
--- a/.github/workflows/mvn-verify-check.yml
+++ b/.github/workflows/mvn-verify-check.yml
@@ -40,22 +40,6 @@ jobs:
         with:
           distribution: 'temurin'
           java-version: 8
-      - name: populate-daily-cache
-        if: steps.cache.outputs.cache-hit != 'true'
-        run: |
-          set -x
-          max_retry=3; delay=30; i=1
-          while true; do
-            mvn help:evaluate -pl dist -Dexpression=included_buildvers \
-            -DforceStdout -PnoSnapshots -q | tr -d ',' | \
-            xargs -n 1 bash -c 'mvn initialize -pl sql-plugin-api -am -Dbuildver=$1' _ && break || {
-            if [[ $i -le $max_retry ]]; then
-              echo "mvn command failed. Retry $i/$max_retry."; ((i++)); sleep $delay; ((delay=delay*2))
-            else
-              echo "mvn command failed. Exit 1"; exit 1
-            fi
-          }
-          done 
       - name: Generate daily cache key
         id: generateCacheKey
         run: |
@@ -68,6 +52,24 @@ jobs:
         with:
           path: ~/.m2
           key: ${{ env.dailyCacheKey }}
+      - name: populate-daily-cache
+        if: steps.cache.outputs.cache-hit != 'true'
+        run: |
+          set -x
+          max_retry=3; delay=30; i=1
+          while true; do
+            for pom_xml in pom.xml scala2.13/pom.xml; do 
+              mvn -f $pom_xml help:evaluate -pl dist -Dexpression=included_buildvers \
+              -DforceStdout -PnoSnapshots -q | tr -d ',' | \
+              xargs -n 1 bash -c 'mvn -f $1 initialize -pl sql-plugin-api -am -Dbuildver=$1' _ $pom_xml;
+            done && break || {
+            if [[ $i -le $max_retry ]]; then
+              echo "mvn command failed. Retry $i/$max_retry."; ((i++)); sleep $delay; ((delay=delay*2))
+            else
+              echo "mvn command failed. Exit 1"; exit 1
+            fi
+          }
+          done 
 
   get-shim-versions-from-dist:
     needs: cache-dependencies
