add retry and ttl config for all stages
Signed-off-by: YanxuanLiu <yanxuanl@nvidia.com>

diff --git a/.github/workflows/mvn-verify-check.yml b/.github/workflows/mvn-verify-check.yml
--- a/.github/workflows/mvn-verify-check.yml
+++ b/.github/workflows/mvn-verify-check.yml
@@ -124,16 +124,22 @@ jobs:
           export JAVA_HOME=${JAVA_HOME_8_X64}
           export PATH=${JAVA_HOME}/bin:${PATH}
           java -version && mvn --version && echo "ENV JAVA_HOME: $JAVA_HOME, PATH: $PATH"
-          # test command
-          mvn -Dmaven.wagon.http.retryHandler.count=3 \
-            -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 \
-            -Daether.connector.http.connectionMaxTtl=25 -B package \
-            -pl integration_tests,tests -am \
-            -P 'individual,pre-merge' \
-            -Dbuildver=${{ matrix.spark-version }} \
-            -Dmaven.scalastyle.skip=true \
-            -Drat.skip=true \
-            ${{ env.COMMON_MVN_FLAGS }}
+          # test command, will retry for 3 times if failed.
+          max_retry=3; i=1
+          while true; do
+            mvn -Dmaven.wagon.http.retryHandler.count=3 \
+              -Dmaven.wagon.httpconnectionManager.ttlSeconds=30 \
+              -Daether.connector.http.connectionMaxTtl=30 -B package \
+              -pl integration_tests,tests -am -P 'individual,pre-merge' \
+              -Dbuildver=${{ matrix.spark-version }} -Dmaven.scalastyle.skip=true \
+              -Drat.skip=true ${{ env.COMMON_MVN_FLAGS }} && break || {
+            if [[ $i -le $max_retry ]]; then
+              echo "mvn command failed. Retry $i/$max_retry."; ((i++)); sleep 3
+            else
+              echo "mvn command failed. Exit 1"; exit 1
+            fi
+          }
+          done
 
   package-tests-scala213:
     needs: get-shim-versions-from-dist
@@ -172,14 +178,22 @@ jobs:
           fi
           # change to Scala 2.13 Directory
           cd scala2.13
-          # test command
-          mvn -Dmaven.wagon.http.retryHandler.count=3 -B package \
-            -pl integration_tests,tests -am \
-            -P 'individual,pre-merge' \
-            -Dbuildver=${{ matrix.spark-version }} \
-            -Dmaven.scalastyle.skip=true \
-            -Drat.skip=true \
-            ${{ env.COMMON_MVN_FLAGS }}
+          # test command, will retry for 3 times if failed.
+          max_retry=3; i=1
+          while true; do
+            mvn -Dmaven.wagon.http.retryHandler.count=3 \
+              -Dmaven.wagon.httpconnectionManager.ttlSeconds=30 \
+              -Daether.connector.http.connectionMaxTtl=30 -B package \
+              -pl integration_tests,tests -am -P 'individual,pre-merge' \
+              -Dbuildver=${{ matrix.spark-version }} -Dmaven.scalastyle.skip=true \
+              -Drat.skip=true ${{ env.COMMON_MVN_FLAGS }} && break || {
+            if [[ $i -le $max_retry ]]; then
+              echo "mvn command failed. Retry $i/$max_retry."; ((i++)); sleep 3
+            else
+              echo "mvn command failed. Exit 1"; exit 1
+            fi
+          }
+          done
 
 
   verify-all-modules:
@@ -209,21 +223,17 @@ jobs:
           export PATH=${JAVA_HOME}/bin:${PATH}
           java -version && mvn --version && echo "ENV JAVA_HOME: $JAVA_HOME, PATH: $PATH"
           # test command, will retry for 3 times if failed.
-          max_retry=3
-          i=1
+          max_retry=3; i=1
           while true; do
-            mvn -Dmaven.wagon.http.retryHandler.count=$max_retry -B verify \
-              -P "individual,pre-merge" \
-              -Dbuildver=${{ matrix.spark-version }} \
-              ${{ env.COMMON_MVN_FLAGS }} \
-            && break || {
+            mvn -Dmaven.wagon.http.retryHandler.count=$max_retry \
+              -Dmaven.wagon.httpconnectionManager.ttlSeconds=30 \
+              -Daether.connector.http.connectionMaxTtl=30 -B verify \
+              -P "individual,pre-merge" -Dbuildver=${{ matrix.spark-version }} \
+              ${{ env.COMMON_MVN_FLAGS }} && break || {
             if [[ $i -le $max_retry ]]; then
-              echo "mvn command failed. Retry $i/$max_retry."
-              ((i++))
-              sleep 3
+              echo "mvn command failed. Retry $i/$max_retry."; ((i++)); sleep 3
             else
-              echo "mvn command failed. Exit 1"
-              exit 1
+              echo "mvn command failed. Exit 1"; exit 1
             fi
           }
           done
@@ -258,8 +268,19 @@ jobs:
           export JAVA_HOME=export JAVA_HOME=${JAVA_HOME_11_X64}
           export PATH=${JAVA_HOME}/bin:${PATH}
           java -version && mvn --version && echo "ENV JAVA_HOME: $JAVA_HOME, PATH: $PATH"
-          # test command
-          ./mvnw -Dmaven.wagon.http.retryHandler.count=3 -B install \
-            -P "individual,pre-merge" \
-            -Dbuildver=${{ needs.get-shim-versions-from-dist.outputs.defaultSparkVersion }} \
-            ${{ env.COMMON_MVN_FLAGS }}
+          # test command, will retry for 3 times if failed.
+          max_retry=3; i=1
+          while true; do
+            ./mvnw -Dmaven.wagon.http.retryHandler.count=3 \
+              -Dmaven.wagon.httpconnectionManager.ttlSeconds=30 \
+              -Daether.connector.http.connectionMaxTtl=30 -B install \
+              -P "individual,pre-merge" \
+              -Dbuildver=${{ needs.get-shim-versions-from-dist.outputs.defaultSparkVersion }} \
+              ${{ env.COMMON_MVN_FLAGS }} && break || {
+            if [[ $i -le $max_retry ]]; then
+              echo "mvn command failed. Retry $i/$max_retry."; ((i++)); sleep 3
+            else
+              echo "mvn command failed. Exit 1"; exit 1
+            fi
+          }
+          done
